version: '4.26.1'
services:
  # Apache webserver service
  webserver:
    container_name: PHP-webServer
    build:
    # Dockerfile path
      context: .
      dockerfile: Dockerfile  
    # Mount the local ./src directory to /var/www/html in the container
    volumes:
      - ./src:/var/www/html 
    # Map port 8000 on the host to port 80 on the container 
    ports:
      - 8000:80
    links:
      - php
    depends_on:
      - postgres

  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.1-apache
    container_name: php_docker
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./src:/var/www

  postgres:
    image: postgres:16.0
    environment:
      POSTGRES_DB: rest_api_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      # Default email for pgAdmin 4
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      # Password for accessing pgAdmin 4
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      # Expose pgadmin on 5050 
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: always
volumes:
  pgadmin_data: